name: LaTeX CI

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Replace placeholders in LaTeX document
        run: |
          PHONE_NUMBER="${{ secrets.PHONE_NUMBER }}"
          EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}"
          sed "s/PHONE_NUMBER_PLACEHOLDER/$PHONE_NUMBER/g" resume.tex > resume_phone.tex
          sed "s/EMAIL_ADDRESS_PLACEHOLDER/$EMAIL_ADDRESS/g" resume_phone.tex > resume_email.tex
          mv resume_email.tex resume.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create gh-pages directory
        run: mkdir gh-pages

      - name: Move PDF to gh-pages directory
        run: mv $GITHUB_WORKSPACE/resume.pdf gh-pages/

      - name: Configure Git and push to gh-pages branch
        run: |
          cd gh-pages
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git init
          git add .
          git commit -m "Update resume.pdf"
          git branch -M main
          git remote add origin "https://github.com/${{ github.repository }}.git"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages

env:
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  EMAIL: ${{ secrets.EMAIL_ADDRESS }}
