name: LaTeX CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Replace placeholders in LaTeX document
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          HOMEPAGE: ${{ vars.HOMEPAGE }}
        run: |
          sed -e "s|PHONE_NUMBER_PLACEHOLDER|${PHONE_NUMBER}|g" \
              -e "s|EMAIL_ADDRESS_PLACEHOLDER|${EMAIL_ADDRESS}|g" \
              -e "s|HOMEPAGE_PLACEHOLDER|${HOMEPAGE}|g" \
              resume.tex > resume_replaced.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume_replaced.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume_replaced.pdf
          if-no-files-found: error
