name: LaTeX CI

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy PDF to GitHub Pages
        run: |
          mkdir -p gh-pages
          mv $GITHUB_WORKSPACE/resume.pdf gh-pages
          cd gh-pages
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git init
          git add .
          git commit -m "Update resume.pdf"
          git branch -M main
          git remote add origin "https://github.com/${{ github.repository }}.git"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
